version: "3.9"

services:
  web:
    build: .
    image: mental_health_web
    command: sh -c "rm -rf ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && 
                    rails db:create db:migrate db:seed"
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/mental_health

  db:
    image: postgres
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5000:5000

  sidekiq:
    image: mental_health_web:latest
    env_file: .env
    command: sidekiq
    volumes:
      - .:/mental_health
    depends_on:
     - redis
     - db

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379

